# 字典抽取

In [5]:
from sklearn.feature_extraction import DictVectorizer

fruit = [{"fruit": "苹果" ,"price": 5}, {"fruit": "橘子" ,"price": 5.9}, {"fruit": "菠萝" ,"price": 9.9}]
"""
特征抽取——字典抽取

"""
vect = DictVectorizer()
result = vect.fit_transform(fruit)

print( result )
print( type(result) )
print( result.toarray() )
print( vect.get_feature_names() )


  (0, 1)	1.0
  (0, 3)	5.0
  (1, 0)	1.0
  (1, 3)	5.9
  (2, 2)	1.0
  (2, 3)	9.9
<class 'scipy.sparse.csr.csr_matrix'>
[[0.  1.  0.  5. ]
 [1.  0.  0.  5.9]
 [0.  0.  1.  9.9]]
['fruit=橘子', 'fruit=苹果', 'fruit=菠萝', 'price']


# 文本抽取
## 英文文本

In [6]:
from sklearn.feature_extraction.text import CountVectorizer

"""
文本特征抽取——CountVectorizer
"""

vect = CountVectorizer()
result = vect.fit_transform(["life is short, I need Doubleone","life is so long, I want always to stay with Lin"])

print( result )
print( type(result) )
print( result.toarray() )
print( vect.get_feature_names() )


  (0, 3)	1
  (0, 2)	1
  (0, 7)	1
  (0, 6)	1
  (0, 1)	1
  (1, 3)	1
  (1, 2)	1
  (1, 8)	1
  (1, 5)	1
  (1, 11)	1
  (1, 0)	1
  (1, 10)	1
  (1, 9)	1
  (1, 12)	1
  (1, 4)	1
<class 'scipy.sparse.csr.csr_matrix'>
[[0 1 1 1 0 0 1 1 0 0 0 0 0]
 [1 0 1 1 1 1 0 0 1 1 1 1 1]]
['always', 'doubleone', 'is', 'life', 'lin', 'long', 'need', 'short', 'so', 'stay', 'to', 'want', 'with']


## 中文文本抽取

In [9]:
import jieba

string1 = "生命像向东流的一江春水，他从最高处发源，冰雪是他的前身。他聚集起许多细流，合成一股有力的洪涛，向下奔注，他曲折的穿过了悬崖峭壁，冲倒了层沙积土，挟卷着滚滚的沙石，快乐勇敢地流走，一路上他享受着他所遭遇的一切：有时候他遇到巉岩前阻，()他愤激地奔腾了起来，怒吼着，回旋着，前波后浪的起伏催逼，直到他过了，冲倒了这危崖他才心平气和的一泻千里。有时候他经过了细细的平沙，斜阳芳草里，看见了夹岸红艳的桃花，他快乐而又羞怯，静静地流着，低低的吟唱着，轻轻地度过这一段浪漫的行程。"
string2 = "一个拥有丰富内在的人，就像在冬月的晚上，在漫天冰雪当中拥有一间明亮、温暖、愉快的圣诞小屋。"
string3 = "一生像似太长，却又太短，待搞清楚有何心愿，一年已经过去，那么四十岁之前若不匆匆把所有该做或不该做之事做妥，之后也无甚作为，所以人人不够时间"

"""
punct = set()
filterpunct = lambda s:''.join(filter(lambda x: x not in punct,s))

words1 = " ".join(jieba.cut(filterpunct(string1)))
"""

words1 = " ".join(jieba.cut(string1))
words2 = " ".join(jieba.cut(string2))
words3 = " ".join(jieba.cut(string3))
# list(words1)

vect = CountVectorizer()
result = vect.fit_transform([words1,words2,words3])

print( result )
print( type(result) )
print( result.toarray() )
print( vect.get_feature_names() )


  (0, 82)	1
  (0, 35)	1
  (0, 72)	1
  (0, 67)	1
  (0, 31)	1
  (0, 23)	1
  (0, 26)	1
  (0, 91)	1
  (0, 94)	1
  (0, 87)	1
  (0, 32)	1
  (0, 6)	1
  (0, 69)	1
  (0, 75)	1
  (0, 34)	1
  (0, 42)	1
  (0, 66)	1
  (0, 85)	1
  (0, 54)	1
  (0, 24)	2
  (0, 74)	1
  (0, 60)	1
  (0, 80)	1
  (0, 73)	1
  (0, 52)	2
  :	:
  (1, 55)	1
  (1, 39)	1
  (1, 44)	1
  (2, 5)	1
  (2, 16)	1
  (2, 40)	1
  (2, 61)	1
  (2, 68)	1
  (2, 51)	1
  (2, 2)	1
  (2, 46)	1
  (2, 98)	1
  (2, 101)	1
  (2, 37)	1
  (2, 12)	1
  (2, 29)	1
  (2, 58)	1
  (2, 10)	1
  (2, 19)	1
  (2, 13)	1
  (2, 18)	1
  (2, 57)	1
  (2, 15)	1
  (2, 9)	1
  (2, 63)	1
<class 'scipy.sparse.csr.csr_matrix'>
[[0 1 0 1 1 0 1 1 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 1 2 1 1 1 1 0 1 1 1 1 1 1
  1 0 1 0 0 1 1 1 0 1 0 1 1 0 1 0 2 1 1 0 1 0 0 0 1 0 1 0 0 0 1 1 0 1 2 1
  1 1 1 1 1 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 0 1]
 [1 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 2 0 0 0 0 1 1 0 0 0 0 0 

# TF-IDF抽取

In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer

tf = TfidfVectorizer()

result =tf.fit_transform([words1,words2,words3])

print( result )
print( type(result) )
print( result.toarray() )
print( vect.get_feature_names() )

  (0, 93)	0.11502736062564178
  (0, 78)	0.11502736062564178
  (0, 3)	0.11502736062564178
  (0, 48)	0.11502736062564178
  (0, 97)	0.11502736062564178
  (0, 36)	0.11502736062564178
  (0, 17)	0.11502736062564178
  (0, 76)	0.11502736062564178
  (0, 102)	0.11502736062564178
  (0, 90)	0.11502736062564178
  (0, 71)	0.11502736062564178
  (0, 86)	0.11502736062564178
  (0, 41)	0.11502736062564178
  (0, 84)	0.11502736062564178
  (0, 92)	0.11502736062564178
  (0, 62)	0.11502736062564178
  (0, 47)	0.11502736062564178
  (0, 88)	0.11502736062564178
  (0, 89)	0.11502736062564178
  (0, 4)	0.11502736062564178
  (0, 50)	0.11502736062564178
  (0, 30)	0.11502736062564178
  (0, 83)	0.11502736062564178
  (0, 20)	0.11502736062564178
  (0, 95)	0.11502736062564178
  :	:
  (1, 59)	0.47702411121907506
  (1, 0)	0.23851205560953753
  (1, 23)	0.18139456604738438
  (2, 63)	0.2132007163556104
  (2, 9)	0.2132007163556104
  (2, 15)	0.2132007163556104
  (2, 57)	0.2132007163556104
  (2, 18)	0.2132007163556104
  (2, 13)	0.