# 归一化

In [3]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range=(0,3)) #默认(0,1)
data = [
    [180,75,90],
    [175,80,19],
    [159,98,34],
    [160,65,50]
]

result = scaler.fit_transform(data)
print(result)

[[3.         0.90909091 3.        ]
 [2.28571429 1.36363636 0.        ]
 [0.         3.         0.63380282]
 [0.14285714 0.         1.30985915]]


# 标准化

In [4]:
from sklearn.preprocessing import StandardScaler


scaler = StandardScaler()
result = scaler.fit_transform(data)
print(result)

[[ 1.25288983 -0.37598039  1.57666489]
 [ 0.70815512  0.0417756  -1.10460953]
 [-1.03499595  1.54569717 -0.53814311]
 [-0.92604901 -1.21149238  0.06608775]]


# 缺失值处理

In [8]:
from sklearn.impute import SimpleImputer
import numpy as np

# help(SimpleImputer)
data = [
    [8,9],
    [np.nan,4],   # 缺失值被该列平均值代替
    [7,2]
]

si = SimpleImputer()
result = si.fit_transform(data)
print(result)

[[8.  9. ]
 [7.5 4. ]
 [7.  2. ]]
